apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      priorityClassName: high-priority 
      containers:
      - name: demo-app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/data"
          name: demo-storage
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/virtualhost/virtualhost.conf
          subPath: virtualhost.conf
          readOnly: true
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      volumes:
      - name: demo-storage
        persistentVolumeClaim:
          claimName: demo-pvc
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: virtualhost.conf
            path: virtualhost.conf