apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  namespace: demo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo-services
  hostPath:
    path: "/mnt/data"