apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asiayo-app-hpa
  namespace: asiayo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asiayo-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60