apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-demo-mysql-primary-0
  labels:
    app: data-demo-mysql-primary-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-mysql
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-demo-mysql-volume-0
  labels:
    app: data-demo-mysql-secondary
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-mysql
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-demo-mysql-volume-1
  labels:
    app: data-demo-mysql-secondary
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-mysql
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql-data