apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asiayo-ingress-1
  namespace: asiayo
spec:
  ingressClassName: asiayo
  tls:
  - hosts:
    - asiayo-1.angusitlab.com
    secretName: angusitlab-tls
  rules:
  - host: asiayo-1.angusitlab.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asiayo-service
            port:
              number: 80