apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asiayo-pvc
  namespace: asiayo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: asiayo-services
  selector:
    matchLabels:
      pv-name: asiayo-pv-1