apiVersion: v1
kind: PersistentVolume
metadata:
  name: asiayo-pv-1
  namespace: asiayo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: asiayo-services
  hostPath:
    path: "/mnt/data"