apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-superset
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo-services
  hostPath:
    path: "/bitnami/postgresql/data"