superset:
  postgresql:
    enabled: true
    volumePermissions:
      enabled: true
    primary:
      persistence:
        storageClass: demo-services
  configOverrides:
    superset_config.py: |
      SECRET_KEY = "ds8932ufjojAJFL@#LJF:LAJ"